[build]
publish = "public"

# Always trigger a rebuild, even if the files haven't changed.
# See https://docs.netlify.com/configure-builds/file-based-configuration/#ignore-builds
ignore = "false"

[build.environment]
HUGO_VERSION = "0.145.0"
GO_VERSION = "1.23.0"